name: Fetch JSON Data

on:
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one?whiteboard_id=147e656f8ddeba8698eaa5caceb66836fceb945598e81c59cd8de750de350a8c > src/resources/data.json

      - name: Save JSON data to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B main 
          git pull
          git add src/resources/data.json  # Change data.`json to data.json
          git commit -m "Update data.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
